test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

cloudflare:
  service: S3
  access_key_id: <%= ENV.fetch("R2_ACCESS_KEY_ID", "") %>
  secret_access_key: <%= ENV.fetch("R2_SECRET_ACCESS_KEY", "") %>
  region: auto
  endpoint: <%= ENV.fetch("R2_ENDPOINT", "") %>
  bucket: brooke-maisy
  request_checksum_calculation: "when_required"
  response_checksum_validation: "when_supported"
